name: Build and Deploy

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  # Dockerhub账户
  DOCKERHUB_REGISTRY: docker.io
  DOCKERHUB_USERNAME: 1715142548
  DOCKERHUB_PASSWORD: wxl5211314
  DOCKERHUB_NAMESPACE: 1715142548
  DOCKERHUB_REPOSITORY: pet-hospital-data
  # 要构建的模块
  TARGET_MODULE: data
  # 拉取其他仓库代码的token
  ADMIN_GITHUB_TOKEN: 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
  # 服务器root密码
  ROOT_PASSWORD: Wxl5211314.0.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [ allParent, data, base, illness, user, gateway, exam, utils, feign ]

    steps:
    - name: Checkout repositories
      uses: actions/checkout@v2
      with:
        repository: SDP-Gang-of-Six/${{ matrix.repository }}
        path: ${{ matrix.repository }}
        ref: main
        token: ${{ env.ADMIN_GITHUB_TOKEN }}

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        cache: maven

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build allParent with Maven
      run: mvn clean install
      working-directory: allParent

    - name: Build final ${{ env.TARGET_MODULE }} jar
      run: mvn clean package
      working-directory: ${{ env.TARGET_MODULE }}

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.DOCKERHUB_REPOSITORY }}

    - name: Build and push Docker images
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ${{ env.TARGET_MODULE }}
        file: ${{ env.TARGET_MODULE }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run command via SSH
      run: sshpass -p "${{ env.ROOT_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@wxl475.cn "sh /root/pet-hospital/${{ env.TARGET_MODULE }}.sh"
