name: Build and Deploy
#1
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Checkout allParent
      uses: actions/checkout@v2
      with:
        repository: SDP-Gang-of-Six/allParent
        path: allParent
        ref: main
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - name: Checkout data
      uses: actions/checkout@v2
      with:
        repository: SDP-Gang-of-Six/data
        path: data
        ref: main
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - name: Checkout base
      uses: actions/checkout@v2
      with:
        repository: SDP-Gang-of-Six/base
        path: base
        ref: main
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - name: Checkout gateway
      uses: actions/checkout@v2
      with:
        repository: SDP-Gang-of-Six/gateway
        path: gateway
        ref: main
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - name: Checkout illness
      uses: actions/checkout@v2
      with:
        repository: SDP-Gang-of-Six/illness
        path: illness
        ref: main
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - name: Checkout user
      uses: actions/checkout@v2
      with:
        repository: SDP-Gang-of-Six/user
        path: user
        ref: main
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - name: Checkout exam
      uses: actions/checkout@v2
      with:
        repository: SDP-Gang-of-Six/exam
        path: exam
        ref: main
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - name: Checkout utils
      uses: actions/checkout@v2
      with:
        repository: SDP-Gang-of-Six/utils
        path: utils
        ref: main
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - name: Checkout feign
      uses: actions/checkout@v2
      with:
        repository: SDP-Gang-of-Six/feign
        path: feign
        ref: main
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build allParent with Maven
      run: mvn clean install
      working-directory: allParent

    - name: Build utils with Maven
      run: mvn clean install
      working-directory: utils

    - name: Build feign with Maven
      run: mvn clean install
      working-directory: feign

    - name: Build final jar
      run: mvn clean package
      working-directory: data
