name: Build and Deploy
#1
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Checkout allParent
      uses: actions/checkout@v2
      with:
        repository: SDP-Gang-of-Six/allParent
        path: allParent
        branch: main

    - name: Build with Maven
      run: mvn clean install

    - name: Checkout utils
      uses: actions/checkout@v2
      with:
        repository: SDP-Gang-of-Six/utils
        path: utils
        branch: main

    - name: Build utils with Maven
      run: mvn clean install
      working-directory: utils

    - name: Checkout feign
      uses: actions/checkout@v2
      with:
        repository: SDP-Gang-of-Six/feign
        path: feign
        branch: main

    - name: Build feign with Maven
      run: mvn clean install
      working-directory: feign

    - name: Build final jar
      run: mvn clean package
